# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amap.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_amap(object):
    def setupUi(self, MainWindow_1):
        self.centralwidget_1 = QtWidgets.QWidget(MainWindow_1)
        self.centralwidget_1.setEnabled(True)
        self.centralwidget_1.setObjectName("centralwidget_1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 871, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.pushButton_amap_subwaystation = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_subwaystation.setObjectName("pushButton_amap_subwaystation")
        self.gridLayout_1.addWidget(self.pushButton_amap_subwaystation, 1, 1, 1, 1)
        self.pushButton_amap_searchpoi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_searchpoi.setObjectName("pushButton_amap_searchpoi")
        self.gridLayout_1.addWidget(self.pushButton_amap_searchpoi, 0, 1, 1, 1)
        self.pushButton_amap_buslinestop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_buslinestop.setObjectName("pushButton_amap_buslinestop")
        self.gridLayout_1.addWidget(self.pushButton_amap_buslinestop, 1, 0, 1, 1)
        self.pushButton_amap_railwaystation = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_railwaystation.setObjectName("pushButton_amap_railwaystation")
        self.gridLayout_1.addWidget(self.pushButton_amap_railwaystation, 1, 2, 1, 1)
        self.pushButton_amap_coordtrans = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_coordtrans.setObjectName("pushButton_amap_coordtrans")
        self.gridLayout_1.addWidget(self.pushButton_amap_coordtrans, 0, 2, 1, 1)
        self.pushButton_amap_routeplan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_routeplan.setObjectName("pushButton_amap_routeplan")
        self.gridLayout_1.addWidget(self.pushButton_amap_routeplan, 0, 0, 1, 1)
        self.pushButton_amap_gt7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_gt7.setObjectName("pushButton_amap_gt7")
        self.gridLayout_1.addWidget(self.pushButton_amap_gt7, 2, 0, 1, 1)
        self.pushButton_amap_fifa = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_fifa.setObjectName("pushButton_amap_fifa")
        self.gridLayout_1.addWidget(self.pushButton_amap_fifa, 2, 1, 1, 1)
        self.pushButton_amap_dota2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_amap_dota2.setObjectName("pushButton_amap_dota2")
        self.gridLayout_1.addWidget(self.pushButton_amap_dota2, 2, 2, 1, 1)
        self.pushButton_amap_backprevious = QtWidgets.QPushButton(self.centralwidget_1)
        self.pushButton_amap_backprevious.setGeometry(QtCore.QRect(550, 510, 131, 23))
        self.pushButton_amap_backprevious.setObjectName("pushButton_amap_backprevious")
        self.pushButton_amap_backmainpage = QtWidgets.QPushButton(self.centralwidget_1)
        self.pushButton_amap_backmainpage.setGeometry(QtCore.QRect(720, 510, 131, 23))
        self.pushButton_amap_backmainpage.setObjectName("pushButton_amap_backmainpage")
        # MainWindow_1.setCentralWidget(self.centralwidget_1)
        # self.menubar_1 = QtWidgets.QMenuBar(MainWindow_1)
        # self.menubar_1.setGeometry(QtCore.QRect(0, 0, 951, 23))
        # self.menubar_1.setObjectName("menubar_1")
        # MainWindow_1.setMenuBar(self.menubar_1)
        # self.statusbar_1 = QtWidgets.QStatusBar(MainWindow_1)
        # self.statusbar_1.setObjectName("statusbar_1")
        # MainWindow_1.setStatusBar(self.statusbar_1)

        self.retranslateUi(MainWindow_1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_1)

    def retranslateUi(self, MainWindow_1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_1.setWindowTitle(_translate("MainWindow_1", "MainWindow"))
        self.pushButton_amap_subwaystation.setText(_translate("MainWindow_1", "地铁站路查询"))
        self.pushButton_amap_searchpoi.setText(_translate("MainWindow_1", "搜索poi"))
        self.pushButton_amap_buslinestop.setText(_translate("MainWindow_1", "公交线路及站点"))
        self.pushButton_amap_railwaystation.setText(_translate("MainWindow_1", "铁路站"))
        self.pushButton_amap_coordtrans.setText(_translate("MainWindow_1", "坐标转换"))
        self.pushButton_amap_routeplan.setText(_translate("MainWindow_1", "路径规划"))
        self.pushButton_amap_gt7.setText(_translate("MainWindow_1", "gt7"))
        self.pushButton_amap_fifa.setText(_translate("MainWindow_1", "fifa"))
        self.pushButton_amap_dota2.setText(_translate("MainWindow_1", "dota2"))
        self.pushButton_amap_backprevious.setText(_translate("MainWindow_1", "返回前一页"))
        self.pushButton_amap_backmainpage.setText(_translate("MainWindow_1", "回到主页"))












