# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keysetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_Form_mainpage_setkeys(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form_mainpage_setkeys):
        Form_mainpage_setkeys.setObjectName("Form_mainpage_setkeys")
        Form_mainpage_setkeys.resize(632, 192)
        self.groupBox_mainpage_setkeys = QtWidgets.QGroupBox(Form_mainpage_setkeys)
        self.groupBox_mainpage_setkeys.setGeometry(QtCore.QRect(40, 50, 471, 121))
        self.groupBox_mainpage_setkeys.setObjectName("groupBox_mainpage_setkeys")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_mainpage_setkeys)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 451, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_mainpage_setkeys = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_mainpage_setkeys.setContentsMargins(0, 0, 0, 0)
        self.formLayout_mainpage_setkeys.setObjectName("formLayout_mainpage_setkeys")
        self.label_mainpage_setkeys_baiduwebkey = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_baiduwebkey.setObjectName("label_mainpage_setkeys_baiduwebkey")
        self.formLayout_mainpage_setkeys.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_mainpage_setkeys_baiduwebkey)
        self.label_mainpage_setkeys_baiduwebkey_show = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_baiduwebkey_show.setText("")
        self.label_mainpage_setkeys_baiduwebkey_show.setObjectName("label_mainpage_setkeys_baiduwebkey_show")
        self.formLayout_mainpage_setkeys.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_mainpage_setkeys_baiduwebkey_show)
        self.label_mainpage_setkeys_baidujskey = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_baidujskey.setObjectName("label_mainpage_setkeys_baidujskey")
        self.formLayout_mainpage_setkeys.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mainpage_setkeys_baidujskey)
        self.label_mainpage_setkeys_baidujskey_show = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_baidujskey_show.setText("")
        self.label_mainpage_setkeys_baidujskey_show.setObjectName("label_mainpage_setkeys_baidujskey_show")
        self.formLayout_mainpage_setkeys.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_mainpage_setkeys_baidujskey_show)
        self.label_mainpage_setkeys_amapwebkey = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_amapwebkey.setObjectName("label_mainpage_setkeys_amapwebkey")
        self.formLayout_mainpage_setkeys.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_mainpage_setkeys_amapwebkey)
        self.label_mainpage_setkeys_amapwebkey_show = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_amapwebkey_show.setText("")
        self.label_mainpage_setkeys_amapwebkey_show.setObjectName("label_mainpage_setkeys_amapwebkey_show")
        self.formLayout_mainpage_setkeys.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_mainpage_setkeys_amapwebkey_show)
        self.label_mainpage_setkeys_osmkey = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_osmkey.setObjectName("label_mainpage_setkeys_osmkey")
        self.formLayout_mainpage_setkeys.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_mainpage_setkeys_osmkey)
        self.label_mainpage_setkeys_googlekey = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_googlekey.setObjectName("label_mainpage_setkeys_googlekey")
        self.formLayout_mainpage_setkeys.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_mainpage_setkeys_googlekey)
        self.label_mainpage_setkeys_osmkey_show = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_osmkey_show.setText("")
        self.label_mainpage_setkeys_osmkey_show.setObjectName("label_mainpage_setkeys_osmkey_show")
        self.formLayout_mainpage_setkeys.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_mainpage_setkeys_osmkey_show)
        self.label_mainpage_setkeys_googlekey_show = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mainpage_setkeys_googlekey_show.setText("")
        self.label_mainpage_setkeys_googlekey_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_mainpage_setkeys_googlekey_show.setObjectName("label_mainpage_setkeys_googlekey_show")
        self.formLayout_mainpage_setkeys.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_mainpage_setkeys_googlekey_show)
        self.comboBox_mainpage_setkeys = QtWidgets.QComboBox(Form_mainpage_setkeys)
        self.comboBox_mainpage_setkeys.setGeometry(QtCore.QRect(40, 20, 101, 22))
        self.comboBox_mainpage_setkeys.setObjectName("comboBox_mainpage_setkeys")
        self.comboBox_mainpage_setkeys.addItem("")
        self.comboBox_mainpage_setkeys.addItem("")
        self.comboBox_mainpage_setkeys.addItem("")
        self.comboBox_mainpage_setkeys.addItem("")
        self.comboBox_mainpage_setkeys.addItem("")
        self.lineEdit_mainpage_setkeys = QtWidgets.QLineEdit(Form_mainpage_setkeys)
        self.lineEdit_mainpage_setkeys.setGeometry(QtCore.QRect(170, 20, 321, 20))
        self.lineEdit_mainpage_setkeys.setObjectName("lineEdit_mainpage_setkeys")
        self.pushButton_mainpage_setkeys_save = QtWidgets.QPushButton(Form_mainpage_setkeys)
        self.pushButton_mainpage_setkeys_save.setGeometry(QtCore.QRect(520, 20, 75, 23))
        self.pushButton_mainpage_setkeys_save.setObjectName("pushButton_mainpage_setkeys_save")
        self.pushButton_mainpage_setkeys_done = QtWidgets.QPushButton(Form_mainpage_setkeys)
        self.pushButton_mainpage_setkeys_done.setGeometry(QtCore.QRect(520, 60, 75, 23))
        self.pushButton_mainpage_setkeys_done.setObjectName("pushButton_mainpage_setkeys_done")

        self.retranslateUi(Form_mainpage_setkeys)
        QtCore.QMetaObject.connectSlotsByName(Form_mainpage_setkeys)

    def retranslateUi(self, Form_mainpage_setkeys):
        _translate = QtCore.QCoreApplication.translate
        Form_mainpage_setkeys.setWindowTitle(_translate("Form_mainpage_setkeys", "设置keys"))
        self.groupBox_mainpage_setkeys.setTitle(_translate("Form_mainpage_setkeys", "Already entered keys"))
        self.label_mainpage_setkeys_baiduwebkey.setText(_translate("Form_mainpage_setkeys", "百度-web-key"))
        self.label_mainpage_setkeys_baidujskey.setText(_translate("Form_mainpage_setkeys", "百度-js-key"))
        self.label_mainpage_setkeys_amapwebkey.setText(_translate("Form_mainpage_setkeys", "高德-web-key"))
        self.label_mainpage_setkeys_osmkey.setText(_translate("Form_mainpage_setkeys", "osm-key"))
        self.label_mainpage_setkeys_googlekey.setText(_translate("Form_mainpage_setkeys", "google-key"))
        self.comboBox_mainpage_setkeys.setItemText(0, _translate("Form_mainpage_setkeys", "百度-web-key"))
        self.comboBox_mainpage_setkeys.setItemText(1, _translate("Form_mainpage_setkeys", "百度-js-key"))
        self.comboBox_mainpage_setkeys.setItemText(2, _translate("Form_mainpage_setkeys", "高德-web-key"))
        self.comboBox_mainpage_setkeys.setItemText(3, _translate("Form_mainpage_setkeys", "osm-key"))
        self.comboBox_mainpage_setkeys.setItemText(4, _translate("Form_mainpage_setkeys", "google-key"))
        self.lineEdit_mainpage_setkeys.setPlaceholderText(_translate("Form_mainpage_setkeys", "enter your key"))
        self.pushButton_mainpage_setkeys_save.setText(_translate("Form_mainpage_setkeys", "save"))
        self.pushButton_mainpage_setkeys_done.setText(_translate("Form_mainpage_setkeys", "done"))
