# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication,QWidget
from keysetting import Ui_Form_mainpage_setkeys
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 841, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_mainpage_baidu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mainpage_baidu.setObjectName("pushButton_mainpage_baidu")
        self.gridLayout.addWidget(self.pushButton_mainpage_baidu, 0, 1, 1, 1)
        self.pushButton_mainpage_google = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mainpage_google.setObjectName("pushButton_mainpage_google")
        self.gridLayout.addWidget(self.pushButton_mainpage_google, 0, 3, 1, 1)
        self.pushButton_mainpage_amap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mainpage_amap.setObjectName("pushButton_mainpage_amap")
        self.gridLayout.addWidget(self.pushButton_mainpage_amap, 0, 0, 1, 1)
        self.pushButton_mainpage_osm = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mainpage_osm.setObjectName("pushButton_mainpage_osm")
        self.gridLayout.addWidget(self.pushButton_mainpage_osm, 0, 2, 1, 1)
        self.pushButton_mainpage_ctrip = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mainpage_ctrip.setObjectName("pushButton_mainpage_ctrip")
        self.gridLayout.addWidget(self.pushButton_mainpage_ctrip, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName("menubar")
        self.menu_key = QtWidgets.QMenu(self.menubar)
        self.menu_key.setObjectName("menu_key")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionkey = QtWidgets.QAction(MainWindow)
        self.actionkey.setObjectName("actionkey")
        self.actionreset_key = QtWidgets.QAction(MainWindow)
        self.actionreset_key.setObjectName("actionreset_key")
        self.menu_key.addAction(self.actionkey)
        self.menu_key.addAction(self.actionreset_key)
        self.menubar.addAction(self.menu_key.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.actionkey.triggered.connect(self.keysettingshow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_mainpage_baidu.setText(_translate("MainWindow", "百度"))
        self.pushButton_mainpage_google.setText(_translate("MainWindow", "Google"))
        self.pushButton_mainpage_amap.setText(_translate("MainWindow", "高德"))
        self.pushButton_mainpage_osm.setText(_translate("MainWindow", "OSM"))
        self.pushButton_mainpage_ctrip.setText(_translate("MainWindow", "携程"))
        self.menu_key.setTitle(_translate("MainWindow", "设置"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionkey.setText(_translate("MainWindow", "key"))
        self.actionreset_key.setText(_translate("MainWindow", "reset key"))

    def keysettingshow(self):
        self.a = Ui_Form_mainpage_setkeys()
        self.a.show()

class TestGUI(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

# class setKey(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.create_UI()
#
#     def create_UI(self):
#         # 文本输入
#         self.le = QtWidgets.QLineEdit(self)
#         self.le.setFixedSize(250,30)
#         self.le.setPlaceholderText('enter your key')
#         self.le.maxLength()
#         self.le.move(140,20)
#
#         self.btn = QtWidgets.QPushButton('save',self)
#         self.btn.setFixedSize(80,30)
#         self.btn.move(410,20)
#         # 点击comfirme
#         self.btn.clicked.connect(self.showcom)
#
#         self.btn2 = QtWidgets.QPushButton('done',self)
#         self.btn2.setFixedSize(80, 30)
#         self.btn2.move(410, 90)
#
#         self.combo = QtWidgets.QComboBox(self)
#         self.combo.addItem('百度-web-key')
#         self.combo.addItem('百度-js-key')
#         self.combo.addItem('高德-web-key')
#         self.combo.addItem('osm-key')
#         self.combo.addItem('google-key')
#         self.combo.move(20, 20)
#         self.combo.setFixedSize(100,30)
#
#         self.setWindowTitle('set your keys')
#
#     def showcom(self):
#         if self.le.text() != '':
#             QtWidgets.QMessageBox.about(self,'status',self.combo.currentText()+' saved!')
#         else:
#             QtWidgets.QMessageBox.warning(self,'status','its empty')


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = TestGUI()
    mainWindow.show()
    sys.exit(app.exec_())